### ISSUE TITLE
Phpwebshell

### ISSUE THREAD

**Issue by S0me1-dev** [wh0Nsq/PetitPotato#1]
https://github.com/wh0amitz/PetitPotato/blob/master/images/image-20221030165622668.png

What kind of webshell are used to run the potato on that picture. Can someone share it  plz?

Thanks a lot for 🥔 potato!!!

**Comment by wh0amitz** [comment]
You can run it through any webshell that has an echo

**Comment by wh0amitz** [comment]
like `PetitPotato.exe 3 whoami`

**Comment by S0me1-dev** [comment]
Thanks I know, but.. look for some nice one cmd view,  like that on screen.
 Wso that I have is not a best one, but still work

This is not an issue , thanks for you work!

**Comment by wh0amitz** [comment]
Ow, I see. The name of this webshell is Behinder:https://github.com/rebeyond/Behinder/releases 。 But I don't know if it supports languages other than Chinese

**Comment by wh0amitz** [comment]
> Thanks I know, but.. look for some nice one cmd view,  like that on screen.
>  Wso that I have is not a best one, but still work
> 
> This is not an issue , thanks for you work!

**Comment by wh0amitz** [comment]
> Thanks I know, but.. look for some nice one cmd view,  like that on screen.
>  Wso that I have is not a best one, but still work
> 
> This is not an issue , thanks for you work!

Ow, I see. The name of this webshell is Behinder:https://github.com/rebeyond/Behinder/releases 。 But I don't know if it supports languages other than Chinese
